include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: false # Uncomment to enable the `prefer_single_quotes` rule
    require_trailing_commas: true # Always require trailing commas
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
# https://dart.dev/tools/linter-rules

formatter:
  page_width: 120
  trailing_commas: preserve